In [2]:
import numpy as np
import pandas as pd

data = {
    'device': ['Cisco', 'Cisco IOS', 'Cisco IUR'],
    'dc': ['dc1', 'dc2', 'dc3'],
    'ip_address': ['10.10.1.1', '10.10.1.2', '10.10.1.3']
}

df = pd.DataFrame(data)
print(df)

      device   dc ip_address
0      Cisco  dc1  10.10.1.1
1  Cisco IOS  dc2  10.10.1.2
2  Cisco IUR  dc3  10.10.1.3

In [9]:
mirai_data = pd.read_csv("Mirai.csv")
print(type(mirai_data))

<class 'pandas.core.frame.DataFrame'>

In [7]:
# data structure formation through IP packet capture 
mirai_series = mirai_data["sport"]
type(mirai_series)

pandas.core.series.Series

In [10]:
# grouping of dataframe using Network packet capture data 
mirai_data.groupby("sport").sum()["insize"]

sport
0           37
1          226
2           30
3           24
4           16
         ...
34798    34797
34800    34800
34801        0
35028    70057
35029        0
Name: insize, Length: 389, dtype: int64

In [11]:
# indexing of packet capture data
mirai_data[0:3]

,intIP,extIP,proto,dport,dir,sport,insize,incount,outsize,outcount,scount,pcount,time
172.16.6.13,192.168.1.24,6,22,1,34538,1760,12,1730,12,1,10,1.577190e+09,Login
172.16.7.6,172.16.5.10,6,22,1,46588,1688,14,1770,12,1,10,1.577189e+09,Login
172.16.1.8,172.16.5.12,6,22,1,48956,1636,13,1770,12,1,10,1.577190e+09,Login

In [12]:
mirai_series[0:3]

172.16.6.13    1760
172.16.7.6     1688
172.16.1.8     1636
Name: sport, dtype: int64

In [13]:
mirai_data.iloc[3]

intIP              172.16.6.5
extIP                       6
proto                      22
dport                       1
dir                     50514
sport                    1636
insize                     13
incount                  1762
outsize                    12
outcount                    1
scount                     10
pcount      1577190285.476619
time                    Login
Name: 172.16.2.9, dtype: object

In [14]:
# statistical processing with describe() to get the descriptive statistics of your data 
mirai_data.describe()

,extIP,proto,dport,dir,sport,insize,incount,outsize,outcount,scount,pcount
count,64026.000000,64026.000000,64026.000000,64026.000000,64026.000000,64026.00000,6.402600e+04,6.402600e+04,64026.000000,64026.000000,6.402600e+04
mean,7.582748,3127.746322,0.667682,36386.791663,236.652251,6.67810,1.098248e+04,4.570772e+03,0.798832,1.050886,1.577189e+09
std,3.896951,3355.622283,0.471048,17745.692764,802.807894,375.75032,5.496426e+05,3.664844e+05,0.516392,2.300251,8.438684e+02
min,2.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000e+00,0.000000e+00,0.000000,0.000000,1.577187e+09
25%,6.000000,80.000000,0.000000,22366.000000,40.000000,1.00000,4.000000e+01,1.000000e+00,1.000000,0.000000,1.577189e+09
50%,6.000000,2160.000000,1.000000,39210.000000,40.000000,1.00000,4.000000e+01,1.000000e+00,1.000000,0.000000,1.577189e+09
75%,6.000000,5512.750000,1.000000,51342.750000,80.000000,2.00000,6.000000e+01,1.000000e+00,1.000000,0.000000,1.577190e+09
max,17.000000,64652.000000,1.000000,65535.000000,35029.000000,35029.00000,3.774702e+07,3.418174e+07,5.000000,26.000000,1.577191e+09

In [21]:
mirai_data["sport"].cumsum()

172.16.6.13         1760
172.16.7.6          3448
172.16.1.8          5084
172.16.2.9          6720
172.16.3.4          8532
                  ...
172.16.100.3    15151893
172.16.100.3    15151894
172.16.100.3    15151895
172.16.100.3    15151896
172.16.100.3    15151897
Name: sport, Length: 64026, dtype: int64

In [ ]:
mirai_data["intIP"].cumsum()